### ISSUE TITLE
Error: Attempting to inject an unknown injection: 'service:notify'

### ISSUE THREAD

**Issue by nick773312** [PrinceCornNM/emberfire-account#1]
After installing the addon it is missing service notify.

**Comment by giffyjif** [comment]
#7

**Comment by conradlz** [comment]
still an issue on fresh installs

**Comment by vkoves** [comment]
@PrinceCornNM - I believe I have also seen this issue, where booting an app when using `emberfire-account` would fail with the error: `Cannot read property 'emberNotify' of undefined`.

Moving `ember-notify` out of `dependencies and into `devDependencies` in the `package.json` resolved the problem for me, but I am unsure if that is a good long-term solution for this issue.

It's also worth noting that it seems that @matvacha tried to resolve the issue by adding `ember-notify` to dependencies, so it could just be that's the wrong place to have that.
